title: "Pratham Barve"
email: "you@example.com"
description: >- 
  M.Tech Cybersecurity student | CEH v12 | Passionate about Pentesting, IAM, Cloud Security.
baseurl: "" # keep this blank
url: "https://prathambarve.github.io"

author:
  name: "Pratham Barve"
  avatar: "/assets/images/yourphoto.jpg"
  bio: "Cybersecurity enthusiast, currently exploring mobile app pentesting and building custom tools."

# Social Links
twitter: yourhandle
linkedin: pratham-barve
github: pratham-barve
