title: "Pratham Barve"
email: "prathambarve206@gmail.com"
description: >- 
  M.Tech Cybersecurity student | CEH v12 | Passionate about Pentesting, IAM, Cloud Security.
baseurl: "" # keep this blank
url: "https://prathambarve.github.io"

author:
  name: "Pratham Barve"
  avatar: "/assets/profile.jpeg"
  bio: "Cybersecurity enthusiast, currently exploring mobile app pentesting and building custom tools."

# Social Links
twitter: yourhandle
linkedin: "https://www.linkedin.com/pratham-barve"
github: "https://www.github.com/Pratham2011"
